name: Build

on:
  push:
    branches:
      - test_ci
  pull_request:
    branches:
      - test_ci
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - run: |
        echo "Building LAB1"
        cd "LAB1"
        cmake -B build
        cmake --build build

    - run: | 
        echo "Building LAB2_training"
        cd "LAB2_training"
        cmake -B build
        cmake --build build

    - run: |
        echo "Building LAB2"
        cd "LAB2"
        cmake -B build
        cmake --build build
        

      